# Generated by Django 4.1.2 on 2022-10-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0002_remove_cliente_id_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mobile',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
