# Generated by Django 4.1.2 on 2022-10-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0003_cliente_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
