# Generated by Django 4.1.2 on 2022-10-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0004_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechalta',
            field=models.DateField(verbose_name='Fecha Alta'),
        ),
    ]
